### ISSUE TITLE
Investigate how to support existing AF_XDP applications that don't support the Handshake proto

### ISSUE THREAD

**Issue by maryamtahhan** [redhat-et/afxdp-network-operator#2]
Currently the AF_XDP device plugin and a pod exchange a handshake to obtain the xsk_map fd. This is shown [here](https://raw.githubusercontent.com/intel/afxdp-plugins-for-kubernetes/main/docs/sequence.png). It will be important however to support existing AF_XDP applications that have not implemented this handshake. The goal of this issue is to investigate the best approach to do this.

**Comment by kot-begemot-uk** [comment]
Wrapper is the only thing which comes to mind. It will not work for everything, but it should do the job for some use cases. Additionally, having the whole thing integrated into container startup can guarantee that the wrapper is preloaded.

**Comment by kot-begemot-uk** [comment]
Do I understand correctly that this is the only thing which we need to support: BPF_MAP_TYPE_XSKMAP

https://docs.kernel.org/bpf/map_xskmap.html

Further to this, am I right that it need only the open/create calls? Once it gets the right FDs we can leave the actual update elem, etc alone.

**Comment by maryamtahhan** [comment]
Resolved - they can use BPF map pinning
